### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by ernilambar**

### CODE REVIEW

**Comment by ernilambar** [comment]
Only SQLite tests are failing. May be due to https://github.com/wp-cli/wp-cli-tests/pull/214 ?

CC @swissspidy

**Comment by swissspidy** [comment]
@ernilambar They are known to fail, see #92

**Comment by swissspidy** [comment]
But the failing MySQL tests still need to be addressed, no? 🤔

**Comment by ernilambar** [comment]
`wp config set DISABLE_WP_CRON true --raw` was recently added and I have no understanding why it was added. I was testing whether that would fix the issue. After few digging I found that `DISABLE_WP_CRON` is defined in wp-cli-tests itself. So I am not sure what is the actual fix for the issue.

**Comment by swissspidy** [comment]
Seems like a mistake to me. Probably added because config-command was broken until yesterday. @schlessera can we revert that?

**Review by schlessera — APPROVED** [review]

**Pull request merged**
